### ISSUE TITLE
2 hubs conflict 

### ISSUE THREAD

**Issue by arjohnson15** [drewgould/homebridge-garageio#2]
I have 2 Garageio Hubs (one for house and one for the shop) they conflict with each other when trying to add to homebridge. any solution for this?

**Comment by drewgould** [comment]
I only have one hub so it hasn’t yet been tested on more than that. What do you mean by “it’s conflicting”? Can you include Homebridge logs?

**Comment by arjohnson15** [comment]
(node:989) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: b946c873-f550-4503-bf81-3ad283b5c234
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:299:10)
    at Server._handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:490:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:41:10)
    at API.emit (events.js:189:13)
    at API.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/api.js:171:8)
    at /homebridge/node_modules/homebridge-garageio/index.js:268:38
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:989) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:989) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


*each hub individually work perfect. its only when I give my email access to doors on both hubs

**Comment by drewgould** [comment]
Can you include the full log from startup?

**Comment by arjohnson15** [comment]
I completely reset my homebridge and only running your plugin. This is the log when I have all 5 doors granted to my email which include 2 garageio hubs. It tries to initialize the 2 doors from first hub but it never goes any farther. 


[4/27/2019, 3:57:16 PM] [homebridge-config-ui-x] Console v4.0.6 is listening on :: port 8581
[4/27/2019, 3:57:17 PM] Loaded config.json with 0 accessories and 1 platforms.
[4/27/2019, 3:57:17 PM] ---
[4/27/2019, 3:57:17 PM] Loaded plugin: homebridge-dummy
[4/27/2019, 3:57:17 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[4/27/2019, 3:57:17 PM] ---
[4/27/2019, 3:57:17 PM] Loaded plugin: homebridge-garageio
[4/27/2019, 3:57:17 PM] Registering platform 'homebridge-garageio.Garageio'
[4/27/2019, 3:57:17 PM] ---
[4/27/2019, 3:57:17 PM] Loaded plugin: homebridge-config-ui-x
[4/27/2019, 3:57:17 PM] Registering platform 'homebridge-config-ui-x.config'
[4/27/2019, 3:57:17 PM] ---
[4/27/2019, 3:57:17 PM] Loading 1 platforms...
[4/27/2019, 3:57:17 PM] [Garageio] Initializing Garageio platform...
[4/27/2019, 3:57:17 PM] Loading 0 accessories...
Setup Payload:
X-HM://0023ISYWYID80
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                  
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[4/27/2019, 3:57:17 PM] Homebridge is running on port 51826.
[4/27/2019, 3:57:18 PM] [Garageio] Initializing platform accessory 'Yamaha (ID: 7722671a1414062e923f4ab01252a3df)'...
[4/27/2019, 3:57:18 PM] [Garageio] Initializing platform accessory 'Golf Cart (ID: a49a875ddc83c0eaa193c2e2c8a20c7a)'...

**Comment by arjohnson15** [comment]
this is what happens when I only assign doors from one of the hubs. they end up initializing 



[4/27/2019, 4:12:47 PM] [homebridge-config-ui-x] Console v4.0.6 is listening on :: port 8581
[4/27/2019, 4:12:47 PM] Loaded config.json with 0 accessories and 1 platforms.
[4/27/2019, 4:12:47 PM] ---
[4/27/2019, 4:12:47 PM] Loaded plugin: homebridge-dummy
[4/27/2019, 4:12:47 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[4/27/2019, 4:12:47 PM] ---
[4/27/2019, 4:12:47 PM] Loaded plugin: homebridge-garageio
[4/27/2019, 4:12:47 PM] Registering platform 'homebridge-garageio.Garageio'
[4/27/2019, 4:12:47 PM] ---
[4/27/2019, 4:12:47 PM] Loaded plugin: homebridge-config-ui-x
[4/27/2019, 4:12:47 PM] Registering platform 'homebridge-config-ui-x.config'
[4/27/2019, 4:12:47 PM] ---
[4/27/2019, 4:12:47 PM] Loading 1 platforms...
[4/27/2019, 4:12:47 PM] [Garageio] Initializing Garageio platform...
[4/27/2019, 4:12:47 PM] Loading 0 accessories...
Setup Payload:
X-HM://0023ISYWY3IMO
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                  
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[4/27/2019, 4:12:47 PM] Homebridge is running on port 51826.
[4/27/2019, 4:12:48 PM] [Garageio] Initializing platform accessory 'Tundra (ID: ee4f03402e618b4c0a2fa01361995cdc)'...
[4/27/2019, 4:12:48 PM] [Garageio] Initializing platform accessory 'Lisa (ID: cd3900cc5dabcaf4015ec3b798d44d45)'...
[4/27/2019, 4:12:48 PM] [Garageio] Initializing platform accessory 'Motorcycle (ID: d1331afed77a039490dd1709d33dc180)'...
[4/27/2019, 4:13:02 PM] [Garageio] Lisa is closed.
[4/27/2019, 4:13:02 PM] [Garageio] Tundra is closed.
[4/27/2019, 4:13:02 PM] [Garageio] Motorcycle is closed.

**Comment by drewgould** [comment]
Thanks for the A/B logs. I just pushed a 1.0.1 update which adds more logging around the response from Garageio. Can you run `npm install homebridge-garageio` to update and then send me the full homebridge logs with both hubs enabled?

It will still fail but you should get a "Garageio devices:" log line before the '[Garageio] Initializing platform accessory' lines.

**Comment by arjohnson15** [comment]
[4/27/2019, 5:23:55 PM] [homebridge-config-ui-x] Console v4.0.6 is listening on :: port 8581
[4/27/2019, 5:23:56 PM] Loaded config.json with 0 accessories and 1 platforms.
[4/27/2019, 5:23:56 PM] ---
[4/27/2019, 5:23:56 PM] Loaded plugin: homebridge-dummy
[4/27/2019, 5:23:56 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[4/27/2019, 5:23:56 PM] ---
[4/27/2019, 5:23:56 PM] Loaded plugin: homebridge-garageio
[4/27/2019, 5:23:56 PM] Registering platform 'homebridge-garageio.Garageio'
[4/27/2019, 5:23:56 PM] ---
[4/27/2019, 5:23:57 PM] Loaded plugin: homebridge-nest
[4/27/2019, 5:23:57 PM] Registering platform 'homebridge-nest.Nest'
[4/27/2019, 5:23:57 PM] ---
[4/27/2019, 5:23:57 PM] Loaded plugin: homebridge-config-ui-x
[4/27/2019, 5:23:57 PM] Registering platform 'homebridge-config-ui-x.config'
[4/27/2019, 5:23:57 PM] ---
[4/27/2019, 5:23:57 PM] Loading 1 platforms...
[4/27/2019, 5:23:57 PM] [Garageio] Initializing Garageio platform...
[4/27/2019, 5:23:57 PM] Loading 0 accessories...
Setup Payload:
X-HM://0023ISYWY3IMO
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                 
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[4/27/2019, 5:23:57 PM] Homebridge is running on port 51826.
[4/27/2019, 5:23:57 PM] [Garageio] Garageio devices:[{"id":"7aff556c60e985545b6a1203abfb99eb","blackbox_code":"20000c2a690932d0","active":true,"number_of_entities_controlled":3,"last_contact":"2019-04-27 19:23:26","software_version":"0","bluetooth_onboard":false,"bluetooth_mac_address":"000000000000","registered":true,"owner_first_name":"Scott","owner_last_name":"Ertle","time_before_door_open_alert":900,"doors":[{"id":"7722671a1414062e923f4ab01252a3df","state":"CLOSED","sensor":false,"light":false,"name":"Yamaha","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 19:23:26","entity_number":1,"user_relationship":"Owner"},{"id":"a49a875ddc83c0eaa193c2e2c8a20c7a","state":"CLOSED","sensor":false,"light":false,"name":"Golf Cart","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 19:23:25","entity_number":2,"user_relationship":"Owner"}]},{"id":"5a0a09ea54c53b6cf8ddf63004dc9411","blackbox_code":"20000c2a6906cea5","active":true,"number_of_entities_controlled":3,"last_contact":"2019-04-27 22:19:46","software_version":"0","bluetooth_onboard":false,"bluetooth_mac_address":"000000000000","registered":true,"owner_first_name":"Scott","owner_last_name":"Ertle","time_before_door_open_alert":900,"doors":[{"id":"ee4f03402e618b4c0a2fa01361995cdc","state":"CLOSED","sensor":false,"light":false,"name":"Tundra","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 19:59:40","entity_number":1,"user_relationship":"Owner"},{"id":"cd3900cc5dabcaf4015ec3b798d44d45","state":"CLOSED","sensor":false,"light":false,"name":"Lisa","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 19:58:30","entity_number":2,"user_relationship":"Owner"},{"id":"d1331afed77a039490dd1709d33dc180","state":"CLOSED","sensor":false,"light":false,"name":"Motorcycle","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 22:19:46","entity_number":3,"user_relationship":"Owner"}]}]
[4/27/2019, 5:23:57 PM] [Garageio] Initializing platform accessory 'Yamaha (ID: 7722671a1414062e923f4ab01252a3df)'...
[4/27/2019, 5:23:57 PM] [Garageio] Initializing platform accessory 'Golf Cart (ID: a49a875ddc83c0eaa193c2e2c8a20c7a)'...

**Comment by arjohnson15** [comment]
I am able to control the 2 door hub for some reason now. the 3 door hub just doesn't show up.

[4/27/2019, 5:28:37 PM] [homebridge-config-ui-x] Console v4.0.6 is listening on :: port 8581
[4/27/2019, 5:28:38 PM] Loaded config.json with 0 accessories and 1 platforms.
[4/27/2019, 5:28:38 PM] ---
[4/27/2019, 5:28:38 PM] Loaded plugin: homebridge-dummy
[4/27/2019, 5:28:38 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[4/27/2019, 5:28:38 PM] ---
[4/27/2019, 5:28:38 PM] Loaded plugin: homebridge-garageio
[4/27/2019, 5:28:38 PM] Registering platform 'homebridge-garageio.Garageio'
[4/27/2019, 5:28:38 PM] ---
[4/27/2019, 5:28:38 PM] Loaded plugin: homebridge-nest
[4/27/2019, 5:28:38 PM] Registering platform 'homebridge-nest.Nest'
[4/27/2019, 5:28:38 PM] ---
[4/27/2019, 5:28:38 PM] Loaded plugin: homebridge-config-ui-x
[4/27/2019, 5:28:38 PM] Registering platform 'homebridge-config-ui-x.config'
[4/27/2019, 5:28:38 PM] ---
[4/27/2019, 5:28:38 PM] Loading 1 platforms...
[4/27/2019, 5:28:38 PM] [Garageio] Initializing Garageio platform...
[4/27/2019, 5:28:38 PM] Loading 0 accessories...
Setup Payload:
X-HM://0023ISYWY3IMO
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[4/27/2019, 5:28:38 PM] Homebridge is running on port 51826.
[4/27/2019, 5:28:39 PM] [Garageio] Garageio devices:[{"id":"7aff556c60e985545b6a1203abfb99eb","blackbox_code":"20000c2a690932d0","active":true,"number_of_entities_controlled":3,"last_contact":"2019-04-27 22:26:50","software_version":"0","bluetooth_onboard":false,"bluetooth_mac_address":"000000000000","registered":true,"owner_first_name":"Scott","owner_last_name":"Ertle","time_before_door_open_alert":900,"doors":[{"id":"7722671a1414062e923f4ab01252a3df","state":"CLOSED","sensor":false,"light":false,"name":"Yamaha","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 19:23:26","entity_number":1,"user_relationship":"Owner"},{"id":"a49a875ddc83c0eaa193c2e2c8a20c7a","state":"CLOSED","sensor":false,"light":false,"name":"Golf Cart","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 22:26:50","entity_number":2,"user_relationship":"Owner"}]},{"id":"5a0a09ea54c53b6cf8ddf63004dc9411","blackbox_code":"20000c2a6906cea5","active":true,"number_of_entities_controlled":3,"last_contact":"2019-04-27 22:19:46","software_version":"0","bluetooth_onboard":false,"bluetooth_mac_address":"000000000000","registered":true,"owner_first_name":"Scott","owner_last_name":"Ertle","time_before_door_open_alert":900,"doors":[{"id":"ee4f03402e618b4c0a2fa01361995cdc","state":"CLOSED","sensor":false,"light":false,"name":"Tundra","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 19:59:40","entity_number":1,"user_relationship":"Owner"},{"id":"cd3900cc5dabcaf4015ec3b798d44d45","state":"CLOSED","sensor":false,"light":false,"name":"Lisa","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 19:58:30","entity_number":2,"user_relationship":"Owner"},{"id":"d1331afed77a039490dd1709d33dc180","state":"CLOSED","sensor":false,"light":false,"name":"Motorcycle","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 22:19:46","entity_number":3,"user_relationship":"Owner"}]}]
[4/27/2019, 5:28:39 PM] [Garageio] Initializing platform accessory 'Yamaha (ID: 7722671a1414062e923f4ab01252a3df)'...
[4/27/2019, 5:28:39 PM] [Garageio] Initializing platform accessory 'Golf Cart (ID: a49a875ddc83c0eaa193c2e2c8a20c7a)'...
[4/27/2019, 5:29:03 PM] [Garageio] Garageio devices:[{"id":"7aff556c60e985545b6a1203abfb99eb","blackbox_code":"20000c2a690932d0","active":true,"number_of_entities_controlled":3,"last_contact":"2019-04-27 22:26:50","software_version":"0","bluetooth_onboard":false,"bluetooth_mac_address":"000000000000","registered":true,"owner_first_name":"Scott","owner_last_name":"Ertle","time_before_door_open_alert":900,"doors":[{"id":"7722671a1414062e923f4ab01252a3df","state":"CLOSED","sensor":false,"light":false,"name":"Yamaha","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 19:23:26","entity_number":1,"user_relationship":"Owner"},{"id":"a49a875ddc83c0eaa193c2e2c8a20c7a","state":"CLOSED","sensor":false,"light":false,"name":"Golf Cart","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 22:26:50","entity_number":2,"user_relationship":"Owner"}]},{"id":"5a0a09ea54c53b6cf8ddf63004dc9411","blackbox_code":"20000c2a6906cea5","active":true,"number_of_entities_controlled":3,"last_contact":"2019-04-27 22:19:46","software_version":"0","bluetooth_onboard":false,"bluetooth_mac_address":"000000000000","registered":true,"owner_first_name":"Scott","owner_last_name":"Ertle","time_before_door_open_alert":900,"doors":[{"id":"ee4f03402e618b4c0a2fa01361995cdc","state":"CLOSED","sensor":false,"light":false,"name":"Tundra","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 19:59:40","entity_number":1,"user_relationship":"Owner"},{"id":"cd3900cc5dabcaf4015ec3b798d44d45","state":"CLOSED","sensor":false,"light":false,"name":"Lisa","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 19:58:30","entity_number":2,"user_relationship":"Owner"},{"id":"d1331afed77a039490dd1709d33dc180","state":"CLOSED","sensor":false,"light":false,"name":"Motorcycle","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 22:19:46","entity_number":3,"user_relationship":"Owner"}]}]
[4/27/2019, 5:29:03 PM] [Garageio] Yamaha is closed.
[4/27/2019, 5:29:03 PM] [Garageio] Garageio devices:[{"id":"7aff556c60e985545b6a1203abfb99eb","blackbox_code":"20000c2a690932d0","active":true,"number_of_entities_controlled":3,"last_contact":"2019-04-27 22:26:50","software_version":"0","bluetooth_onboard":false,"bluetooth_mac_address":"000000000000","registered":true,"owner_first_name":"Scott","owner_last_name":"Ertle","time_before_door_open_alert":900,"doors":[{"id":"7722671a1414062e923f4ab01252a3df","state":"CLOSED","sensor":false,"light":false,"name":"Yamaha","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 19:23:26","entity_number":1,"user_relationship":"Owner"},{"id":"a49a875ddc83c0eaa193c2e2c8a20c7a","state":"CLOSED","sensor":false,"light":false,"name":"Golf Cart","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 22:26:50","entity_number":2,"user_relationship":"Owner"}]},{"id":"5a0a09ea54c53b6cf8ddf63004dc9411","blackbox_code":"20000c2a6906cea5","active":true,"number_of_entities_controlled":3,"last_contact":"2019-04-27 22:19:46","software_version":"0","bluetooth_onboard":false,"bluetooth_mac_address":"000000000000","registered":true,"owner_first_name":"Scott","owner_last_name":"Ertle","time_before_door_open_alert":900,"doors":[{"id":"ee4f03402e618b4c0a2fa01361995cdc","state":"CLOSED","sensor":false,"light":false,"name":"Tundra","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 19:59:40","entity_number":1,"user_relationship":"Owner"},{"id":"cd3900cc5dabcaf4015ec3b798d44d45","state":"CLOSED","sensor":false,"light":false,"name":"Lisa","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 19:58:30","entity_number":2,"user_relationship":"Owner"},{"id":"d1331afed77a039490dd1709d33dc180","state":"CLOSED","sensor":false,"light":false,"name":"Motorcycle","active":true,"bluetooth_sensor":false,"bluetooth_sensor_mac_address":"000000000000","bluetooth_sensor_battery_level":0,"door_auto_close_enabled":false,"door_auto_close_delay":0,"image":"","last_toggled":"2019-04-27 22:19:46","entity_number":3,"user_relationship":"Owner"}]}]
[4/27/2019, 5:29:03 PM] [Garageio] Golf Cart is closed.

**Comment by arjohnson15** [comment]
I rebooted homebridge and on bootup it loaded the 3 door hub this time and the 2 door didn't show up. 
The hub that loads its doors are operational.

**Comment by drewgould** [comment]
Give 1.0.2 a try.

**Comment by drewgould** [comment]
Give 1.0.3 a try.

**Comment by arjohnson15** [comment]
looks like you got it! they all show up and are working now! great work! C
an probably update with the advanced logging back off if you wish to clean it back up.
